[package]
name = "virtual_whiteboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.6"

[dependencies.clap]
version = "4.4.8"
features = ["derive"]